[package]
name = "wswor"
version = "0.1.0"
authors = ["F5XS <f5xs.0000a@gmail.com>"]
edition = "2018"

[features]
FLOAT32 = []
gitversion = []

[dependencies]
rand = "0.8"
rand_distr = "0.4"
failure = "0.1"
git-version = "0.3"
